name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.7
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
      - name: Build with Maven
        run: mvn package -DskipTests
      - run: mkdir staging && cp web/target/*.war staging
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
